# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile/Profile.proto

require 'google/protobuf'

require_relative '../common/Command_pb'


descriptor_data = "\n\x15profile/Profile.proto\x12\rskywalking.v3\x1a\x14\x63ommon/Command.proto\"\\\n\x17ProfileTaskCommandQuery\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x17\n\x0fserviceInstance\x18\x02 \x01(\t\x12\x17\n\x0flastCommandTime\x18\x03 \x01(\x03\"\x83\x01\n\x0eThreadSnapshot\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x16\n\x0etraceSegmentId\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x10\n\x08sequence\x18\x04 \x01(\x05\x12)\n\x05stack\x18\x05 \x01(\x0b\x32\x1a.skywalking.v3.ThreadStack\"%\n\x0bThreadStack\x12\x16\n\x0e\x63odeSignatures\x18\x01 \x03(\t\"S\n\x17ProfileTaskFinishReport\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x17\n\x0fserviceInstance\x18\x02 \x01(\t\x12\x0e\n\x06taskId\x18\x03 \x01(\t2\x90\x02\n\x0bProfileTask\x12[\n\x16getProfileTaskCommands\x12&.skywalking.v3.ProfileTaskCommandQuery\x1a\x17.skywalking.v3.Commands\"\x00\x12M\n\x0f\x63ollectSnapshot\x12\x1d.skywalking.v3.ThreadSnapshot\x1a\x17.skywalking.v3.Commands\"\x00(\x01\x12U\n\x10reportTaskFinish\x12&.skywalking.v3.ProfileTaskFinishReport\x1a\x17.skywalking.v3.Commands\"\x00\x42\x97\x01\n5org.apache.skywalking.apm.network.language.profile.v3P\x01Z<skywalking.apache.org/repo/goapi/collect/language/profile/v3\xaa\x02\x1dSkyWalking.NetworkProtocol.V3b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Skywalking
  module V3
    ProfileTaskCommandQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.ProfileTaskCommandQuery").msgclass
    ThreadSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.ThreadSnapshot").msgclass
    ThreadStack = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.ThreadStack").msgclass
    ProfileTaskFinishReport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.ProfileTaskFinishReport").msgclass
  end
end
