# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language-agent/Meter.proto

require 'google/protobuf'

require_relative '../common/Command_pb'


descriptor_data = "\n\x1alanguage-agent/Meter.proto\x12\rskywalking.v3\x1a\x14\x63ommon/Command.proto\"$\n\x05Label\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"M\n\x10MeterBucketValue\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\x01\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x12\x1a\n\x12isNegativeInfinity\x18\x03 \x01(\x08\"U\n\x10MeterSingleValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x06labels\x18\x02 \x03(\x0b\x32\x14.skywalking.v3.Label\x12\r\n\x05value\x18\x03 \x01(\x01\"u\n\x0eMeterHistogram\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x06labels\x18\x02 \x03(\x0b\x32\x14.skywalking.v3.Label\x12/\n\x06values\x18\x03 \x03(\x0b\x32\x1f.skywalking.v3.MeterBucketValue\"\xbe\x01\n\tMeterData\x12\x36\n\x0bsingleValue\x18\x01 \x01(\x0b\x32\x1f.skywalking.v3.MeterSingleValueH\x00\x12\x32\n\thistogram\x18\x02 \x01(\x0b\x32\x1d.skywalking.v3.MeterHistogramH\x00\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x17\n\x0fserviceInstance\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x42\x08\n\x06metric\"B\n\x13MeterDataCollection\x12+\n\tmeterData\x18\x01 \x03(\x0b\x32\x18.skywalking.v3.MeterData2\xa7\x01\n\x12MeterReportService\x12@\n\x07\x63ollect\x12\x18.skywalking.v3.MeterData\x1a\x17.skywalking.v3.Commands\"\x00(\x01\x12O\n\x0c\x63ollectBatch\x12\".skywalking.v3.MeterDataCollection\x1a\x17.skywalking.v3.Commands\"\x00(\x01\x42s\n3org.apache.skywalking.apm.network.language.agent.v3P\x01Z:skywalking.apache.org/repo/goapi/collect/language/agent/v3b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Skywalking
  module V3
    Label = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.Label").msgclass
    MeterBucketValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.MeterBucketValue").msgclass
    MeterSingleValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.MeterSingleValue").msgclass
    MeterHistogram = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.MeterHistogram").msgclass
    MeterData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.MeterData").msgclass
    MeterDataCollection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.MeterDataCollection").msgclass
  end
end
