# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging/Logging.proto

require 'google/protobuf'

require_relative '../common/Common_pb'
require_relative '../common/Command_pb'


descriptor_data = "\n\x15logging/Logging.proto\x12\rskywalking.v3\x1a\x13\x63ommon/Common.proto\x1a\x14\x63ommon/Command.proto\"\xea\x01\n\x07LogData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x17\n\x0fserviceInstance\x18\x03 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x04 \x01(\t\x12(\n\x04\x62ody\x18\x05 \x01(\x0b\x32\x1a.skywalking.v3.LogDataBody\x12\x31\n\x0ctraceContext\x18\x06 \x01(\x0b\x32\x1b.skywalking.v3.TraceContext\x12$\n\x04tags\x18\x07 \x01(\x0b\x32\x16.skywalking.v3.LogTags\x12\r\n\x05layer\x18\x08 \x01(\t\"\x9e\x01\n\x0bLogDataBody\x12\x0c\n\x04type\x18\x01 \x01(\t\x12&\n\x04text\x18\x02 \x01(\x0b\x32\x16.skywalking.v3.TextLogH\x00\x12&\n\x04json\x18\x03 \x01(\x0b\x32\x16.skywalking.v3.JSONLogH\x00\x12&\n\x04yaml\x18\x04 \x01(\x0b\x32\x16.skywalking.v3.YAMLLogH\x00\x42\t\n\x07\x63ontent\"\x17\n\x07TextLog\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x17\n\x07JSONLog\x12\x0c\n\x04json\x18\x01 \x01(\t\"\x17\n\x07YAMLLog\x12\x0c\n\x04yaml\x18\x01 \x01(\t\"G\n\x0cTraceContext\x12\x0f\n\x07traceId\x18\x01 \x01(\t\x12\x16\n\x0etraceSegmentId\x18\x02 \x01(\t\x12\x0e\n\x06spanId\x18\x03 \x01(\x05\":\n\x07LogTags\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.skywalking.v3.KeyStringValuePair2R\n\x10LogReportService\x12>\n\x07\x63ollect\x12\x16.skywalking.v3.LogData\x1a\x17.skywalking.v3.Commands\"\x00(\x01\x42\x85\x01\n,org.apache.skywalking.apm.network.logging.v3P\x01Z3skywalking.apache.org/repo/goapi/collect/logging/v3\xaa\x02\x1dSkyWalking.NetworkProtocol.V3b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Skywalking
  module V3
    LogData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.LogData").msgclass
    LogDataBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.LogDataBody").msgclass
    TextLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.TextLog").msgclass
    JSONLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.JSONLog").msgclass
    YAMLLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.YAMLLog").msgclass
    TraceContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.TraceContext").msgclass
    LogTags = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.LogTags").msgclass
  end
end
