# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language-agent/ConfigurationDiscoveryService.proto

require 'google/protobuf'

require_relative '../common/Command_pb'


descriptor_data = "\n2language-agent/ConfigurationDiscoveryService.proto\x12\rskywalking.v3\x1a\x14\x63ommon/Command.proto\"9\n\x18\x43onfigurationSyncRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t2z\n\x1d\x43onfigurationDiscoveryService\x12Y\n\x13\x66\x65tchConfigurations\x12\'.skywalking.v3.ConfigurationSyncRequest\x1a\x17.skywalking.v3.Commands\"\x00\x42\x98\x01\n3org.apache.skywalking.apm.network.language.agent.v3P\x01Z?skywalking.apache.org/repo/goapi/collect/agent/configuration/v3\xaa\x02\x1dSkyWalking.NetworkProtocol.V3b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Skywalking
  module V3
    ConfigurationSyncRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.ConfigurationSyncRequest").msgclass
  end
end
