# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language-agent/JVMMetricCompat.proto

require 'google/protobuf'

require_relative '../common/Command_pb'
require_relative 'JVMMetric_pb'


descriptor_data = "\n$language-agent/JVMMetricCompat.proto\x1a\x14\x63ommon/Command.proto\x1a\x1elanguage-agent/JVMMetric.proto2b\n\x16JVMMetricReportService\x12H\n\x07\x63ollect\x12\".skywalking.v3.JVMMetricCollection\x1a\x17.skywalking.v3.Commands\"\x00\x42\xab\x01\n:org.apache.skywalking.apm.network.language.agent.v3.compatP\x01ZAskywalking.apache.org/repo/goapi/collect/language/agent/v3/compat\xb8\x01\x01\xaa\x02$SkyWalking.NetworkProtocol.V3.Compatb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

