# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language-agent/MeterCompat.proto

require 'google/protobuf'

require_relative '../common/Command_pb'
require_relative 'Meter_pb'


descriptor_data = "\n language-agent/MeterCompat.proto\x1a\x14\x63ommon/Command.proto\x1a\x1alanguage-agent/Meter.proto2V\n\x12MeterReportService\x12@\n\x07\x63ollect\x12\x18.skywalking.v3.MeterData\x1a\x17.skywalking.v3.Commands\"\x00(\x01\x42\xab\x01\n:org.apache.skywalking.apm.network.language.agent.v3.compatP\x01ZAskywalking.apache.org/repo/goapi/collect/language/agent/v3/compat\xb8\x01\x01\xaa\x02$SkyWalking.NetworkProtocol.V3.Compatb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

