# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: language-agent/Meter.proto for package 'skywalking.v3'
# Original file comments:
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

require 'grpc'
require_relative 'Meter_pb'

module Skywalking
  module V3
    module MeterReportService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'skywalking.v3.MeterReportService'

        # Meter data is reported in a certain period. The agent/SDK should report all collected metrics in this period through one stream.
        # The whole stream is an input data set, client should onComplete the stream per report period.
        rpc :collect, stream(::Skywalking::V3::MeterData), ::Skywalking::V3::Commands
        # Reporting meter data in bulk mode as MeterDataCollection.
        # By using this, each one in the stream would be treated as a complete input for MAL engine,
        # comparing to `collect (stream MeterData)`, which is using one stream as an input data set.
        rpc :collectBatch, stream(::Skywalking::V3::MeterDataCollection), ::Skywalking::V3::Commands
      end

      Stub = Service.rpc_stub_class
    end
  end
end
