# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: browser/BrowserPerfCompat.proto

require 'google/protobuf'

require_relative '../common/Command_pb'
require_relative 'BrowserPerf_pb'


descriptor_data = "\n\x1f\x62rowser/BrowserPerfCompat.proto\x1a\x14\x63ommon/Command.proto\x1a\x19\x62rowser/BrowserPerf.proto2\xb3\x01\n\x12\x42rowserPerfService\x12L\n\x0f\x63ollectPerfData\x12\x1e.skywalking.v3.BrowserPerfData\x1a\x17.skywalking.v3.Commands\"\x00\x12O\n\x10\x63ollectErrorLogs\x12\x1e.skywalking.v3.BrowserErrorLog\x1a\x17.skywalking.v3.Commands\"\x00(\x01\x42\xab\x01\n:org.apache.skywalking.apm.network.language.agent.v3.compatP\x01ZAskywalking.apache.org/repo/goapi/collect/language/agent/v3/compat\xb8\x01\x01\xaa\x02$SkyWalking.NetworkProtocol.V3.Compatb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

