# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: management/Management.proto

require 'google/protobuf'

require_relative '../common/Common_pb'
require_relative '../common/Command_pb'


descriptor_data = "\n\x1bmanagement/Management.proto\x12\rskywalking.v3\x1a\x13\x63ommon/Common.proto\x1a\x14\x63ommon/Command.proto\"\x84\x01\n\x12InstanceProperties\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x17\n\x0fserviceInstance\x18\x02 \x01(\t\x12\x35\n\nproperties\x18\x03 \x03(\x0b\x32!.skywalking.v3.KeyStringValuePair\x12\r\n\x05layer\x18\x04 \x01(\t\"J\n\x0fInstancePingPkg\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x17\n\x0fserviceInstance\x18\x02 \x01(\t\x12\r\n\x05layer\x18\x03 \x01(\t2\xb5\x01\n\x11ManagementService\x12X\n\x18reportInstanceProperties\x12!.skywalking.v3.InstanceProperties\x1a\x17.skywalking.v3.Commands\"\x00\x12\x46\n\tkeepAlive\x12\x1e.skywalking.v3.InstancePingPkg\x1a\x17.skywalking.v3.Commands\"\x00\x42\x8b\x01\n/org.apache.skywalking.apm.network.management.v3P\x01Z6skywalking.apache.org/repo/goapi/collect/management/v3\xaa\x02\x1dSkyWalking.NetworkProtocol.V3b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Skywalking
  module V3
    InstanceProperties = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.InstanceProperties").msgclass
    InstancePingPkg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("skywalking.v3.InstancePingPkg").msgclass
  end
end
